/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.spbstu

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun test(foo: Int?, bar: Int): Int {
    var i = foo
    if (i == null) {
        return bar
    }
    return i
}

fun main() {
    var a: Any? = 0
    println(App().greeting)
}
